### ISSUE TITLE
CORS needs to be fixed

### ISSUE THREAD

**Issue by adarsh1001111** [Innovateninjas/Paws-Backend#12]
<img width="1200" alt="Screenshot 2024-05-28 at 7 54 24 PM" src="https://github.com/Innovateninjas/Paws-Backend/assets/130575709/1019bfb3-7681-4cb0-8caf-7629c59a1b70">
i found this error while trying to run the backend server on localhost.
@codewarnab we need some fix on this

**Comment by Anirban-Majumder** [comment]
@adarsh1001111 It has been fixed in [this commit](https://github.com/Innovateninjas/Paws-Backend/commit/5de08bc3232202c1d16482012ac5d43da4530cfa) ,Please make sure to pull the latest version, directly from github using `git pull origin main`.
